apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: jpgse3e4r-dotnet-basic
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-ded3d0d3f5.ka8f.p3.openshiftapps.com/rhtap/rhtap-qe-dotnet-basic:e74e4909e1d11527bb24af9c272b4c398d54a8d8@sha256:ba1741cd64cf1364f4f977ce882089bbbb402b98a7748a4744cc5844c0fd1f95
          name: container-image
